### ISSUE TITLE
Código SMS incorrecto

### ISSUE THREAD

**Issue by AlexMnrs** [deividgp/AutenticacioWebVacunacio#1]
Buenas,

Estoy probando tu aplicación y no reconoce bien el código del SMS. El código que introduce es "g: bas". 

No sé de dónde lo saca o qué significa. Esa cadena de caracteres no existe ni en el index.js ni en el correo (estoy utilizando Gmail) del SMS reenviado, pero por más veces que lo ejecuto, siempre introduce lo mismo.

¿Alguna idea de qué puede estar pasando?

¡Gracias!

Edit: He probado con Outlook y pasa lo mismo, me introduce un código incorrecto, en este caso "=C3=A9".

**Comment by deividgp** [comment]
Hola.

Es posible que sea debido al método de extracción del código SMS del correo ya que he utilizado la función slice con un inicio y un final constantes:
![imagen](https://user-images.githubusercontent.com/25442941/124607242-f0578080-de6d-11eb-8b94-656cfdf03ac1.png)
Como se puede ver aquí los carácteres "=C3=A9" siempre coinciden ya que corresponden a la palabra "accés", solo tengo que tomar como referencia los carácteres que hay al lado del código para que funcione.
![imagen](https://user-images.githubusercontent.com/25442941/124608645-29dcbb80-de6f-11eb-91dd-83e0e7b9bc5f.png)
Después investigaré el problema con Gmail ya que ahora mismo no sé qué puede ser así que mantén el "issue" en abierto, te mantendré informado.

Gracias.

**Comment by deividgp** [comment]
Ya he modificado la extracción del código, espero que esta vez funcione.

**Comment by AlexMnrs** [comment]
Hola David,

Efectivamente ahora sí funciona, al menos con la opción de autenticación. Introduce el código del SMS correctamente y te deja en la pantalla donde debes elegir si vacunarte en el Cap o en un centro de vacunación masivo. Entiendo que eso debes elegirlo manualmente, ya que de ahí no pasa.

Sin embargo, con la opción de ejecutar cada X minutos, abre el navegador con una pestaña en blanco y ahí se queda. Supongo que todavía no está implementado.

Por ahora con la primera opción ya estoy más que satisfecho, ¡muchas gracias!

**Comment by deividgp** [comment]
> Efectivamente ahora sí funciona, al menos con la opción de autenticación. Introduce el código del SMS correctamente y te deja en la pantalla donde debes elegir si vacunarte en el Cap o en un centro de vacunación masivo. Entiendo que eso debes elegirlo manualmente, ya que de ahí no pasa.

Correcto, ya que esta opción está enfocada exclusivamente a la entrada de datos.

> Sin embargo, con la opción de ejecutar cada X minutos, abre el navegador con una pestaña en blanco y ahí se queda. Supongo que todavía no está implementado.

Es normal ya que en el campo de segundos tengo puesto un 0 así que se ejecuta cada minuto y 0 segundos aunque todavía le queda lo más importante, que es comprobar los centros de vacunación masiva disponibles y enviar un correo según la variable en .env.

> Por ahora con la primera opción ya estoy más que satisfecho, ¡muchas gracias!

A ti por la ayuda :) .

**Comment by AlexMnrs** [comment]
Buenas,

Reabro el issue para avisar de que actualicé los archivos con los del repo porque vi que sacaste un par de versiones nuevas y vuelve a pasar lo mismo con los códigos del SMS. He tenido que restaurar los archivos a la versión anterior para seguir utilizándolo.

Un saludo!

**Comment by deividgp** [comment]
Hola de nuevo,

Ya está arreglado en teoría. El poblema ha surgido debido a la implementación de la lectura del "from" del mail que hice ayer ya que supuse que el campo "from" siempre se lee en segundo lugar:
![imagen](https://user-images.githubusercontent.com/25442941/124922706-0e51ec00-dffa-11eb-8def-b3aa1409d8d1.png)
Pero no ha sido el caso así que el switch case ha resultado ser inútil por eso lo he cambiado por un if else:
![imagen](https://user-images.githubusercontent.com/25442941/124923474-bd8ec300-dffa-11eb-8c52-218ff98aec93.png)
Además, ahora puedes ejecutar la aplicación con "npm start".

Saludos.
